# Generated by Django 2.0.2 on 2018-03-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffsequwebs', '0002_debruijnsequence_dbmodel_markovsequence_dbmodel_repetitivesequence_dbmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='debruijnsequence_dbmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='markovsequence_dbmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repetitivesequence_dbmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
