# Generated by Django 2.0.2 on 2018-03-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scaffsequwebs', '0003_auto_20180314_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debruijnsequence_dbmodel',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='markovsequence_dbmodel',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='repetitivesequence_dbmodel',
            old_name='date',
            new_name='datetime',
        ),
    ]
