# Generated by Django 2.0.2 on 2018-03-14 20:00

from django.db import migrations, models
import scaffsequwebs.models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffsequwebs', '0004_auto_20180314_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debruijnsequence_dbmodel',
            name='datetime',
            field=models.DateTimeField(default=scaffsequwebs.models.now),
        ),
        migrations.AlterField(
            model_name='markovsequence_dbmodel',
            name='datetime',
            field=models.DateTimeField(default=scaffsequwebs.models.now),
        ),
        migrations.AlterField(
            model_name='repetitivesequence_dbmodel',
            name='datetime',
            field=models.DateTimeField(default=scaffsequwebs.models.now),
        ),
    ]
